### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by weiancheng** [pokk/programming-practice#1]
### 5. dynamic programming
- LCS
- LIS
- ED
### 8. graph
- DFS
### 9. NP complete

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/153132494254570/153133148661309)

**Comment by weiancheng** [comment]
1111

**Comment by pokk** [comment]
We will not follow this one.
I close this issue.

[--- Commented from Asana.com
#commenter Jieyi
---[aa]
