### ISSUE TITLE
Optimal Strategy for a Game

### ISSUE THREAD

**Issue by weiancheng** [pokk/programming-practice#18]
http://www.geeksforgeeks.org/dynamic-programming-set-31-optimal-strategy-for-a-game/

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/153132494254570/153133148312027)

**Comment by pokk** [comment]
Just come! I'm not afraid.

[--- Commented from Asana.com
#commenter Jieyi
---[aa]

**Comment by pokk** [comment]
Why didn't change anything?

[--- Commented from Asana.com
#commenter Jieyi
---[aa]

**Comment by pokk** [comment]
Temporally close this issue.

[--- Commented from Asana.com
#commenter Jieyi
---[aa]
