### ISSUE TITLE
Dynamic Programming - Minimum Partition

### ISSUE THREAD

**Issue by weiancheng** [pokk/programming-practice#7]
http://www.geeksforgeeks.org/partition-a-set-into-two-subsets-such-that-the-difference-of-subset-sums-is-minimum/

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/153132494254570/153133148662466)

**Comment by pokk** [comment]
Temporally close this issue.

[--- Commented from Asana.com
#commenter Jieyi
---[aa]
